name: Tu dong deploy len InfinityFree
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Lay code moi nhat
      uses: actions/checkout@v4

    - name: Day file len host qua FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Đẩy nội dung bên trong folder backend lên
        local-dir: ./be/ 
        server-dir: ./fastfood.is-best.net/htdocs/ 
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          .env
          **/storage/*.php